# theme = 'ayu_dark'
# theme = 'gruvbox_dark_hard'
# theme = 'default'
theme = 'boo-berry'

[editor]
mouse=true
bufferline = 'always'

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden=false
ignore=false

[editor.soft-wrap]
enable=true

[editor.statusline]
left=["mode", "spinner", "version-control"]
right=["file-name","diagnostics", "workspace-diagnostics", "selections", "position", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
display-messages=true
display-inlay-hints=false
snippets=true

# At most one section each of 'keys.normal', 'keys.insert' and 'keys.select'
[keys.normal]
C-f = ":format"
C-s = ":w" # Maps the Control-s to the typable command :w which is an alias for :write (save file)
C-q = ":q" 
C-x = ":buffer-close" 
C-X = ":buffer-close!" 
g = { a = "code_action" } # Maps `ga` to show possible code actions
"ret" = ["open_below", "normal_mode"] # Maps the enter key to open_below then re-enter normal mode

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
